### ISSUE TITLE
pkgdown online documentation

### ISSUE THREAD

**Issue by SamCH93** [florafauna/ReplicationSuccess#47]
Has anybody experience with [pkgdown](https://pkgdown.r-lib.org/)? I have never used it but I guess it would provide an easy way to generate a nice online documentation.

**Comment by florafauna** [comment]
not high priority. but we would then probably change the 'url' in the DESCRIPTION file to that page url. So, it would be nice to have it before the CRAN submission. 
I tried it but the vignette is not shown on the page (small changes are needed) and it would be nice to build the page with a github action. I will try it with a new repository to not mess with this one.

**Comment by florafauna** [comment]
including Rnw (instead of Rmd) vignettes in the webpage seems to be tricky. I tried https://github.com/r-lib/pkgdown/issues/781 but it didn't work right away.

**Comment by SamCH93** [comment]
Thanks for trying. Maybe we could try to migrate the vignette to Rmd at some point and for now don't include it on pkgdown? Is pkgdown otherwise working fine?

**Comment by florafauna** [comment]
jap, I'll make a pull request soon.

**Comment by florafauna** [comment]
https://github.com/florafauna/ReplicationSuccess/pull/65#issue-687664872
