### ISSUE TITLE
add more publications to the CITATION file?

### ISSUE THREAD

**Issue by florafauna** [florafauna/ReplicationSuccess#61]

**Comment by SamCH93** [comment]
I can do that, but is it common practice to have several citations in the CITATION file? Which one at which place? I guess people who use the pkg will cite at most one paper (if any)

**Comment by florafauna** [comment]
Some packages do list multiple publications, e.g., https://cran.r-project.org/web/packages/gstat/citation.html
I see it as a way to promote the research.

I would put the most important on top...
